# SPDX-FileCopyrightText: 2022 Perillamint.
#
# SPDX-License-Identifier: CC0-1.0

name: license check
on:
  push:
    branches:
      - '*'

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - name: Clippy
        uses: qernal/github-actions-rust-clippy@v1.6.0
      - name: FSFE REUSE
        uses: fsfe/reuse-action@v1
        with:
          args: --include-submodules lint
